// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKnQE3GOJKSeXdMPveVqT1m02rgLNmKM',
    appId: '1:148121296226:web:ced2803a777db81163e03b',
    messagingSenderId: '148121296226',
    projectId: 'clubedoproduto-a1564',
    authDomain: 'clubedoproduto-a1564.firebaseapp.com',
    storageBucket: 'clubedoproduto-a1564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyfXaTDwWb1vIdEbsnGA5seOIUjEtdCDw',
    appId: '1:148121296226:android:0042bbd7a57d0fcc63e03b',
    messagingSenderId: '148121296226',
    projectId: 'clubedoproduto-a1564',
    storageBucket: 'clubedoproduto-a1564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyfXaTDwWb1vIdEbsnGA5seOIUjEtdCDw',
    appId: '1:148121296226:ios:32a527342150777389956b',
    messagingSenderId: '148121296226',
    projectId: 'clubedoproduto-a1564',
    storageBucket: 'clubedoproduto-a1564.appspot.com',
    androidClientId:
        '148121296226-8dga73jjtr36sd82cd5ijhgcu0p14p3g.apps.googleusercontent.com',
    iosClientId:
        '148121296226-2magqnhq5chvmvj75v287hngt3qb13rr.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.stackFood',
  );
}
